name: Deploy Dashboard

on:
  push:
    branches: [ main ]
    paths:
      - '1StopDashboard/**'
  # Allow manual triggering
  workflow_dispatch:

# Permissions needed for GitHub Pages deployment
permissions:
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install Dependencies
        run: |
          cd 1StopDashboard
          # Clean install to avoid dependency issues
          rm -rf node_modules
          npm ci || npm install

      - name: Build
        run: |
          cd 1StopDashboard
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run build
          # Debug output to show build results
          echo "Build completed. Contents of build directory:"
          ls -la build/
          
      - name: Add cache control headers for JSON files
        run: |
          # Create .htaccess file with cache control directives
          echo "# Disable caching for data files" > 1StopDashboard/build/.htaccess
          echo "<FilesMatch \"\\.(json)$\">" >> 1StopDashboard/build/.htaccess
          echo "Header set Cache-Control \"no-store, no-cache, must-revalidate, max-age=0\"" >> 1StopDashboard/build/.htaccess
          echo "Header set Pragma \"no-cache\"" >> 1StopDashboard/build/.htaccess
          echo "Header set Expires \"Wed, 11 Jan 1984 05:00:00 GMT\"" >> 1StopDashboard/build/.htaccess
          echo "</FilesMatch>" >> 1StopDashboard/build/.htaccess
          
          # Also add a version timestamp to force cache invalidation
          echo "// Version: $(date +%s)" > 1StopDashboard/build/version.js
          
          # Show the content of the htaccess file
          echo "Created .htaccess file:"
          cat 1StopDashboard/build/.htaccess

      - name: Deploy to proper directory
        run: |
          # Create the destination directory if it doesn't exist
          mkdir -p 1stop/dashboard
          # Copy the build output to the correct directory
          cp -R 1StopDashboard/build/* 1stop/dashboard/
          # Add a timestamp to force cache invalidation
          echo "<!-- Build: $(date +%s) -->" >> 1stop/dashboard/index.html
          # Add version info to the data files
          echo "// Generated: $(date +%s)" > 1stop/dashboard/version.js
          echo "{\"build_time\": \"$(date)\", \"build_timestamp\": $(date +%s)}" > 1stop/dashboard/build-info.json
          # Debug information
          echo "Contents of 1stop/dashboard:"
          ls -la 1stop/dashboard/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .  # Deploy the entire repository
          branch: gh-pages
          clean: false  # Don't remove existing files outside our target
          clean-exclude: |
            **/*
            !1stop/dashboard/**
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Wait for GitHub Pages to deploy
        run: |
          echo "Waiting for GitHub Pages to deploy..."
          # Sleep to allow GitHub Pages to update
          sleep 60
          
      - name: Verify deployment
        run: |
          echo "Verifying deployment..."
          node 1StopDashboard/check-deployment.js 