name: Deploy Dashboard

on:
  push:
    branches: [ main ]
    paths:
      - '1StopDashboard/**'
  # Allow manual triggering
  workflow_dispatch:

# Permissions needed for GitHub Pages deployment
permissions:
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.2'
          # Disable caching to avoid the dependency resolution error
          # cache: 'npm'
          # cache-dependency-path: '**/package-lock.json'

      - name: Install Dependencies
        run: |
          cd 1StopDashboard
          # Clean install to avoid dependency issues
          rm -rf node_modules
          npm install

      - name: Build
        run: |
          cd 1StopDashboard
          export NODE_OPTIONS=--openssl-legacy-provider
          # Disable treating warnings as errors
          export CI=false
          # Run the prepare-data and verify scripts to ensure correct revenue data
          node prepare-data.js
          node verify-revenue-data.js
          npm run build
          # Debug output to show build results
          echo "Build completed. Contents of build directory:"
          ls -la build/

      - name: Add version timestamp
        run: |
          # Add a version timestamp to force cache invalidation
          echo "// Version: $(date +%s)" > 1StopDashboard/build/version.js
          echo "{\"build_time\": \"$(date)\", \"build_timestamp\": $(date +%s)}" > 1StopDashboard/build/build-info.json

      - name: Deploy to proper directory
        run: |
          # Create the destination directory if it doesn't exist
          mkdir -p 1stop/dashboard
          # Copy the build output to the correct directory
          cp -R 1StopDashboard/build/* 1stop/dashboard/
          # Add a timestamp to force cache invalidation
          echo "<!-- Build: $(date +%s) -->" >> 1stop/dashboard/index.html
          # Debug information
          echo "Contents of 1stop/dashboard:"
          ls -la 1stop/dashboard/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: 1stop/dashboard  # Only deploy the dashboard directory
          target-folder: 1stop/dashboard  # Deploy to the specific dashboard folder
          branch: gh-pages
          clean: true  # Clean the target directory
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Wait for GitHub Pages to deploy
        run: |
          echo "Waiting for GitHub Pages to deploy..."
          # Sleep to allow GitHub Pages to update
          sleep 60
          
      - name: Verify deployment
        run: |
          echo "Verifying deployment..."
          node 1StopDashboard/check-deployment.js 