name: Direct Revenue Data Fix

on:
  # Allow manual triggering
  workflow_dispatch:

# Permissions needed for GitHub Pages deployment
permissions:
  contents: write

jobs:
  fix-revenue-data:
    runs-on: ubuntu-latest
    steps:
      - name: Display Emergency Fix Info
        run: |
          echo "==================== EMERGENCY REVENUE FIX ===================="
          echo "This is a direct fix to update the revenue data to the correct value"
          echo "Total revenue should be: $310,395.84"
          echo "================================================================"
      - name: Checkout GitHub Pages branch 🛎️
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      
      - name: Check GitHub repository contents
        run: |
          echo "Examining actual files in the gh-pages branch..."
          
          # List the root directory
          echo "Root directory contents:"
          ls -la
          
          # Check if 1stop directory exists
          if [ -d "1stop" ]; then
            echo "✅ 1stop directory exists"
            # List contents of 1stop
            echo "1stop directory contents:"
            ls -la 1stop
            
            # Check if dashboard directory exists
            if [ -d "1stop/dashboard" ]; then
              echo "✅ dashboard directory exists"
              # List contents of dashboard
              echo "dashboard directory contents:"
              ls -la 1stop/dashboard
            else
              echo "❌ dashboard directory NOT FOUND"
              # Create it
              mkdir -p 1stop/dashboard
              echo "Created dashboard directory"
            fi
          else
            echo "❌ 1stop directory NOT FOUND"
            # Create the directories
            mkdir -p 1stop/dashboard
            echo "Created 1stop/dashboard directories"
          fi
      
      - name: Create revenue data files
        run: |
          echo "Creating revenue data files..."
          
          # Create the essential revenue_data.json file
          echo "{" > 1stop/dashboard/revenue_data.json
          echo "  \"total_revenue\": 310395.84," >> 1stop/dashboard/revenue_data.json
          echo "  \"cities\": {" >> 1stop/dashboard/revenue_data.json
          echo "    \"LYGRRATQ7EGG2\": { \"name\": \"London\", \"revenue\": 158429.89, \"percentage\": 51.0 }," >> 1stop/dashboard/revenue_data.json
          echo "    \"LXMC6DWVJ5N7W\": { \"name\": \"Hamilton\", \"revenue\": 55925.11, \"percentage\": 18.0 }," >> 1stop/dashboard/revenue_data.json
          echo "    \"LDK6Z980JTKXY\": { \"name\": \"Kitchener-Waterloo\", \"revenue\": 45629.86, \"percentage\": 14.7 }," >> 1stop/dashboard/revenue_data.json
          echo "    \"L4NE8GPX89J3A\": { \"name\": \"Ottawa\", \"revenue\": 44269.42, \"percentage\": 14.3 }," >> 1stop/dashboard/revenue_data.json
          echo "    \"LG0VGFKQ25XED\": { \"name\": \"Calgary\", \"revenue\": 5610.99, \"percentage\": 1.8 }" >> 1stop/dashboard/revenue_data.json
          echo "  }," >> 1stop/dashboard/revenue_data.json
          echo "  \"emergency_fix\": true," >> 1stop/dashboard/revenue_data.json
          echo "  \"timestamp\": \"$(date)\"" >> 1stop/dashboard/revenue_data.json
          echo "}" >> 1stop/dashboard/revenue_data.json
          
          # Create a data subdirectory for alternative paths
          mkdir -p 1stop/dashboard/data
          
          # Create a copy in the data subdirectory
          cp 1stop/dashboard/revenue_data.json 1stop/dashboard/data/revenue_data.json
          
          # Create a simplified verification file instead of complex HTML
          echo "Creating simplified verification file..."
          echo "<!DOCTYPE html>" > 1stop/dashboard/revenue-verify.html
          echo "<html><head><title>Revenue Verification</title></head>" >> 1stop/dashboard/revenue-verify.html
          echo "<body>" >> 1stop/dashboard/revenue-verify.html
          echo "<h1>Revenue Data Verification</h1>" >> 1stop/dashboard/revenue-verify.html
          echo "<p>Total Revenue is $310,395.84</p>" >> 1stop/dashboard/revenue-verify.html
          echo "<script>" >> 1stop/dashboard/revenue-verify.html
          echo "fetch('./revenue_data.json?' + new Date().getTime())" >> 1stop/dashboard/revenue-verify.html
          echo "  .then(response => response.json())" >> 1stop/dashboard/revenue-verify.html
          echo "  .then(data => {" >> 1stop/dashboard/revenue-verify.html
          echo "    document.body.innerHTML += '<p>Loaded Revenue: $' + data.total_revenue + '</p>';" >> 1stop/dashboard/revenue-verify.html
          echo "    document.body.innerHTML += '<pre>' + JSON.stringify(data, null, 2) + '</pre>';" >> 1stop/dashboard/revenue-verify.html
          echo "  })" >> 1stop/dashboard/revenue-verify.html
          echo "  .catch(err => document.body.innerHTML += '<p>Error: ' + err.message + '</p>');" >> 1stop/dashboard/revenue-verify.html
          echo "</script>" >> 1stop/dashboard/revenue-verify.html
          echo "</body></html>" >> 1stop/dashboard/revenue-verify.html
          
          # Verify the files
          echo "Created files:"
          ls -la 1stop/dashboard/
          echo "Data directory contents:"
          ls -la 1stop/dashboard/data/
          
          # Show file content
          echo "Content of revenue_data.json:"
          cat 1stop/dashboard/revenue_data.json
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add all files in the dashboard directory
          git add 1stop/dashboard/revenue_data.json
          git add 1stop/dashboard/data
          git add 1stop/dashboard/revenue-verify.html
          
          # Commit the changes
          git commit -m "Emergency fix: Update revenue data files with correct figures ($310,395.84)"
          
          # Push the changes
          git push origin gh-pages 